#!/usr/bin/env bash
#script that installs nginx web server and displays hello world string
apt-get -y update
apt-get -y install nginx
echo "Hello world!" > /var/www/html/index.nginx-debian.html
service nginx start
